---
- name: Create Azure VM
  hosts: localhost
  collections: 
  - azure.azcollection
  gather_facts: false
  connection: local
  tasks:
  - name: Create Public IP address
    azure_rm_publicipaddress:
      resource_group: Junior_training
      allocation_method: Static
      name: newVMIP2
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Interfaces
    azure_rm_networkinterface:
      resource_group: Junior_training
      name: "{{new_vm}}_NIC"
      virtual_network: junior_training_vnet
      subnet: default
      public_ip_name: newVMIP2
      security_group: "{{new_vm}}_SG"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: Junior_training
      name: "{{new_vm}}"
      vm_size: Standard_E4s_v3
      admin_username: "{{admin_username}}"
      admin_password: "{{admin_password}}"
      network_interfaces: "{{new_vm}}_NIC"
      public_ip_allocation_method: static
      #subscription_id: 3a49f80b-be29-4847-9d66-724a67d9f3d4
      #ssh_password_enabled: false
      #ssh_public_keys:
      #  - path: /home/azureuser/.ssh/authorized_keys
      #    key_data: "<key_data>"
      #network_interfaces: cvo_nic1
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
