---
- name: Create Azure VM
  hosts: localhost
  collections: 
  - azure.azcollection
  gather_facts: false
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: Junior_training
      name: "{{new_vm_name}}"
      vm_size: Standard_E4s_v3
      admin_username: "{{admin_username}}"
      admin_password: "{{admin_password}}"
      #subscription_id: 3a49f80b-be29-4847-9d66-724a67d9f3d4
      #ssh_password_enabled: false
      #ssh_public_keys:
      #  - path: /home/azureuser/.ssh/authorized_keys
      #    key_data: "<key_data>"
      #network_interfaces: cvo_nic1
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
