---
- name: Create Azure volume Clone
  hosts: ansible
  #connection: local
  gather_facts: false
  collections:
  - azure.azcollection
  tasks:
  - name: create flexclone
    na_ontap_volume_clone:
        state: present
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ hostname }}"
        vserver: "{{ vserver_name }}"
        parent_volume: "{{ parent_volume }}"
        volume: "{{ clone_name }}"
        policy: export-svm_azurecvo
        parent_snapshot: "{{ snapshot_name }}"
        junction_path: "/{{ clone_name}}"
        
