---

- name: ontap
  hosts: ansible
  gather_facts: no
  connection: local

  tasks:
  - name: create linux VM
    vmware_guest:
     hostname: "{{ vcenter_hostname }}"
     username: "{{ username }}"
     password: "{{ password }}"
     esxi_hostname: "{{ esxi_hostname }}"
     datacenter: "{{ datacenter }}"
     folder: "{{ folder }}"
     name: "{{ item }}"
     state: poweredon
     guest_id: "{{ guest_id }}"
     disk:
     - size_gb: "{{ disk_size }}"
       type: thin
       datastore: "{{ datastore }}"
     networks:
     - name: "{{ network_name }}"
       ip: "{{ ip_address }}"
       netmask: "{{ netmask }}"
       gateway: "{{ gateway }}"
       dns_servers: "{{ dns_servers }}"
       start_connected: yes
     hardware:
       memory_mb: "{{ memory_size }}"
       num_cpus: "{{ num_cpus }}"
     customization:
      dns_servers: "{{ dns_servers }}"
      hostname: "{{ item }}"
     template: "{{ template }}"
     validate_certs: false
    with_items: "{{ servers }}"
