---
- hosts: 20.214.111.44
  tasks:
  - name: install nfs client
    yum: name=nfs-utils state=present

  - name: verify mount directory
    file:
     path: "{{mount_path}}"
     state: directory

  - name: mount nfs vol
    mount:
      state: mounted
      path: "{{mount_path}}"
      src: 172.18.0.9:/peer_target_vol_clone
      fstype: nfs

