---
- hosts: 115.144.174.92
  gather_facts: no
  tasks:
  - name: install nfs client
    yum: name=nfs-utils state=present

  - name: verify mount directory
    file:
     path: /mnt/final2
     state: directory

  - name: mount nfs vol
    mount:
      state: mounted
      path: /mnt/final2
      src: 115.144.174.86:/ansible_onprem_vol2
      fstype: nfs
