---
- hosts: 20.214.111.44
  name: install nfs and mount volume
  become: yes
  become_user: root
  tasks:
  - name: install nfs client
    yum: name=nfs-utils state=present

  - name: verify mount directory
    file:
     path: /mnt/test
     state: directory

  - name: mount nfs vol
    mount:
      state: mounted
      path: /mnt/test
      src: 172.18.0.9:/peer_target_vol_clone
      fstype: nfs

