---
- hosts: 115.144.174.92
  gather_facts: no
  tasks:
  - name: install nfs client
    yum: name=nfs-utils state=present

  - name: verify mount directory
    file:
     path: /mnt/test
     state: directory

  - name: mount nfs vol
    mount:
      state: mounted
      path: /mnt/test
      src: "{{volume_mount_path}}"
      fstype: nfs
